### ISSUE TITLE
Port content from CodePlex

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit.github.io#11]
Review, update, and port applicable content from CodePlex:

* [x] http://xunit.codeplex.com/wikipage?title=WhyDidWeBuildXunit&referringTitle=Home
* [x] http://xunit.codeplex.com/wikipage?title=Comparisons&referringTitle=Home
* [x] http://xunit.codeplex.com/wikipage?title=HowToUseMSBuild&referringTitle=Home
* [x] http://xunit.codeplex.com/wikipage?title=HowToUseTeamCity&referringTitle=Home
* [x] http://xunit.codeplex.com/wikipage?title=HowToUseCcNet&referringTitle=Home
* [x] http://xunit.codeplex.com/wikipage?title=HowToCompile&referringTitle=Home
* [ ] http://xunit.codeplex.com/wikipage?title=XmlFormat&referringTitle=Home

**Comment by SeanKilleen** [comment]
If you want, I could look at porting this text as-is, and then you could review it for content. Figured I could save you some time at least.

The docs appear to mostly use HTML instead of markdown. Is that by design / still the preference, or is markdown preferred? (I'm fine with either; my blog is currently running on jekyll/markdown).

**Comment by bradwilson** [comment]
Our doc site uses HTML, so leaving them as HTML is not much of an issue. Most of these pages will need to be updated for v2, which is why I haven't just copied them over as-is. They just haven't made it near the top of the priority list yet.

We'd be happy to take any PRs you want to send our way. :)

**Comment by bradwilson** [comment]
Although the comparisons page has been ported, the assertion list is woefully out of date w/rt to all of the test frameworks, including xUnit.net. http://xunit.github.io/docs/comparisons.html#assertions

**Comment by SeanKilleen** [comment]
@bradwilson would it make sense to eventually organize these points of improvement as their own issues that people can jump in on? For example, if we break it down a bit I'm sure I can tackle (or at least begin to tackle) some of them.

**Comment by bradwilson** [comment]
Good point, I'll just open two new issues.
