### ISSUE TITLE
Is it possible to run xunit.runner.dnx against Microsoft.Framework.Runtime version 1.0.0.beta5?

### ISSUE THREAD

**Issue by rajajhansi** [xunit/xunit.github.io#20]
My WEB API project is using Microsoft.Framework.Runtime version 1.0.0.beta5 and xunit.runner.dnx has references to Microsoft.Framework.Runtime.Interfaces version 1.0.0.beta4. I'm trying to run an API  Integration test using Microsoft.AspNet.TestHost.TestServer and it needs to get IApplicaitonEnvironment using CallContextServiceLocator.Locator.ServiceProvider. Because CallContextServiceLocator is  available in Microsoft.Framework.Runtime.Abstractions (Runtime 1.0.0.beta5 has references to Abstractions) as well as Microsoft.Framework.Runtime.Interfaces (Runtime 1.0.0.beta4 has references to Interfaces which is downloaded by xunit.runner.dnx), I can't compile and run. Instead of the standard answer of stick to one version of the Runtime, is there a workaround?

**Comment by bradwilson** [comment]
2.1 Beta 2 (the currently supported beta release) is built against DNX 1.0 Beta 4.

If you want to use an unsupported CI build that should work with DNX 1.0 Beta 5, then you can use builds from our MyGet server: https://www.myget.org/F/xunit/.
